### PR TITLE
Support prediction and a big refactor

### PR DESCRIPTION
**Pull request by jingedawang**
+ Implement predict method.
+ Move python files in algorithm and backend to stock_predictor folder.
+ Finish the overall workflow of the prediction service.
+ Add installation and usages in README. Users and developers could setup the service according to it.

### CODE REVIEW

**Review by sanzgiri — COMMENTED** [review]
Hi @jingedawang 

Overall comments: I think maybe we can add a config at the top level to select between CN vs US stocks.

In terms of the directory structure / crontab:

It relies on qlib to be installed in a particular path (under ~/projects) I did not see listed in the setup

Also is there another way to run the data update i.e without using tmux? tmux is not a standard utility, it is not present by default on a Mac. The particualr command in the crontab relies on an existing tmux session "update-data" already running on your machine.
Also the python you are invoking  in the crontab has to be from the same environment as your qlib code. You may want to specify that explicitly if you are using multiple virtual environments/conda etc, this is what your login script would have to switch to.

**Comment by jingedawang** [comment]
Hi @sanzgiri , thanks for the comment.

> Overall comments: I think maybe we can add a config at the top level to select between CN vs US stocks.

That will be good, but it needs further works to prepare the data and extra logics. I will focus on CN stocks first. If you would like to help on this, that will be great.

> In terms of the directory structure / crontab:
> 
> It relies on qlib to be installed in a particular path (under ~/projects) I did not see listed in the setup

Yes, this problem should be solved. It's not easy to find the Qlib repo by code, I would like to add some instructions in the README for this.

> Also is there another way to run the data update i.e without using tmux? tmux is not a standard utility, it is not present by default on a Mac. The particualr command in the crontab relies on an existing tmux session "update-data" already running on your machine. Also the python you are invoking in the crontab has to be from the same environment as your qlib code. You may want to specify that explicitly if you are using multiple virtual environments/conda etc, this is what your login script would have to switch to.

At first, I was using crontab directly. But it didn't print any log, which is hard to debug when it fails. So, I changed to use tmux to run the update command. Do you have any suggestion on this?

**Comment by jingedawang** [comment]
Hi @sanzgiri ,

I tried to get rid of tmux and use crontab directly but failed. It's not easy to activate the conda environment in crontab job, looks like the non-interactive bash is not well-supported for conda.
Also, it's not easy to set a universal path in crontab script because crontab always uses HOME directory as working directory, so I have to use a hard-code project path in update_data.crontab file.

I updated the README to explain the related operations. If you have better solution, please let me know.

Thanks,
Jinge

**Review by sanzgiri — APPROVED** [review]
Hi @jingedawang - please merge these changes, I will add in some changes that the simplify the cron process later.

**Pull request merged**
